// ============================================================================
// CodeExporter.h
// ============================================================================
// Pilar 1 — Feature Consolidation (DRY Principle)
//
// SEBELUMNYA: Logika byte generation & file IO berceceran di:
//   - CodeGenerator.h   (DerivePatchBytes inline, SaveFile inline)
//   - ClassesTab.cpp    (Copy-paste DerivePatchBytes ~80 baris)
//   - ESPManager.h      (Util::FileWriter inline di ExportAll())
//
// SESUDAHNYA: Satu namespace CodeExporter yang menjadi single source of truth.
//   - CodeGenerator.h  → hanya include CodeExporter.h, panggil CodeExporter::*
//   - ClassesTab.cpp   → hapus blok DerivePatchBytes inline, panggil CodeExporter::DerivePatchBytes()
//   - ESPManager.h     → panggil CodeExporter::SaveFile() sebagai ganti Util::FileWriter inline
//
// ============================================================================
#pragma once

#include <string>
#include <sstream>
#include <fstream>
#include <vector>
#include <unordered_map>
#include <algorithm>
#include <cctype>
#include <cstring>
#include <cstdio>
#include <cstdint>

#include "Il2cpp/Il2cpp.h"
#include "Il2cpp/il2cpp-class.h"
#include "Includes/Logger.h"
#include "Includes/Utils.h"   // GetLibBase()
#include "Tool/Util.h"        // DirCodegen(), FileWriter

// ============================================================================
// Forward declarations
// ============================================================================
namespace ClassesTabTypes {
    struct OriginalMethodBytes {
        std::vector<uint8_t> bytes;
        std::string text;
    };
}

// ============================================================================
// CGPatchEntry — data satu patch yang akan diekspor
// ============================================================================
struct CGPatchEntry {
    std::string           className;
    std::string           methodName;
    std::string           featureName;   // safe identifier: ClassName_MethodName
    uintptr_t             rva       = 0; // Offset dari library base — STABIL antar restart
    std::string           libName;       // "libil2cpp.so"
    size_t                libSize   = 0; // Ukuran region untuk GG region-size filter
    std::vector<uint8_t>  bytesOriginal;
    std::vector<uint8_t>  bytesPatched;
    std::string           patchText;
    std::string           returnTypeName;
};

// ============================================================================
// namespace CodeExporter
// Single Source of Truth untuk semua operasi export.
// ============================================================================
namespace CodeExporter {

// ─────────────────────────────────────────────────────────────────────────────
// SECTION 1: String / Byte Helpers
// ─────────────────────────────────────────────────────────────────────────────

/// Byte array → "AA BB CC" (spaced hex, untuk GG Lua hexON/hexOFF)
inline std::string BytesToSpacedHex(const std::vector<uint8_t>& b) {
    std::ostringstream ss;
    for (size_t i = 0; i < b.size(); i++) {
        char h[4]; snprintf(h, sizeof(h), "%02X", b[i]);
        ss << h;
        if (i + 1 < b.size()) ss << " ";
    }
    return ss.str();
}

/// Byte array → "{0xAA,0xBB,0xCC}" (C array literal, untuk AutoGenerated.h)
inline std::string BytesToCArray(const std::vector<uint8_t>& b) {
    std::ostringstream ss;
    ss << "{";
    for (size_t i = 0; i < b.size(); i++) {
        char h[6]; snprintf(h, sizeof(h), "0x%02X", b[i]);
        ss << h;
        if (i + 1 < b.size()) ss << ",";
    }
    ss << "}";
    return ss.str();
}

/// String → UPPERCASE
inline std::string ToUpper(std::string s) {
    std::transform(s.begin(), s.end(), s.begin(), ::toupper);
    return s;
}

/// String → identifier C++ yang valid (non-alnum/_ diganti '_')
inline std::string Sanitize(const std::string& s) {
    std::string out;
    out.reserve(s.size());
    for (char c : s) {
        out += (std::isalnum((unsigned char)c) || c == '_') ? c : '_';
    }
    if (!out.empty() && std::isdigit((unsigned char)out[0]))
        out = "_" + out;
    return out;
}

// ─────────────────────────────────────────────────────────────────────────────
// SECTION 2: Type Mapping
// ─────────────────────────────────────────────────────────────────────────────

/// IL2CPP type name → C++ type string
inline std::string TypeToC(const std::string& typeName) {
    if (typeName=="System.Int32"  ||typeName=="Int32")   return "int32_t";
    if (typeName=="System.Int64"  ||typeName=="Int64")   return "int64_t";
    if (typeName=="System.UInt32" ||typeName=="UInt32")  return "uint32_t";
    if (typeName=="System.UInt64" ||typeName=="UInt64")  return "uint64_t";
    if (typeName=="System.Int16"  ||typeName=="Int16")   return "int16_t";
    if (typeName=="System.Boolean"||typeName=="Boolean") return "bool";
    if (typeName=="System.Single" ||typeName=="Single")  return "float";
    if (typeName=="System.Double" ||typeName=="Double")  return "double";
    if (typeName=="System.Byte"   ||typeName=="Byte")    return "uint8_t";
    if (typeName=="System.String" ||typeName=="String")  return "Il2CppString*";
    if (typeName.find("Vector3")    != std::string::npos) return "Vector3";
    if (typeName.find("Vector2")    != std::string::npos) return "Vector2";
    if (typeName.find("Quaternion") != std::string::npos) return "Quaternion";
    return "Il2CppObject*";
}

/// IL2CPP type name → GameGuardian type string
inline std::string TypeToGG(const std::string& typeName) {
    if (typeName=="System.Int32"  ||typeName=="Int32")   return "DWORD";
    if (typeName=="System.Int64"  ||typeName=="Int64")   return "QWORD";
    if (typeName=="System.UInt32" ||typeName=="UInt32")  return "DWORD";
    if (typeName=="System.Single" ||typeName=="Single")  return "FLOAT";
    if (typeName=="System.Boolean"||typeName=="Boolean") return "BYTE";
    if (typeName=="System.Byte"   ||typeName=="Byte")    return "BYTE";
    if (typeName.find("Vector3")  != std::string::npos) return "FLOAT";
    return "DWORD";
}

// ─────────────────────────────────────────────────────────────────────────────
// SECTION 3: ARM64 Patch Byte Derivation  ← SINGLE SOURCE OF TRUTH
//
// BUG FIX: ClassesTab.cpp menggunakan LDR offset 0x18000040/0x58000040/0x1C000040
//          (target register W0/X0/S0 dengan encoding berbeda) sedangkan
//          CodeGenerator.h menggunakan 0x18000060/0x58000060/0x1C000060.
//          Keduanya salah encoding untuk register 0 (W0=0x00, bukan 0x40/0x60).
//
//          Encoding benar ARM64 LDR literal untuk Wn/Xn/Sn dengan register n=0:
//            LDR W0, label  → 0x18000040  (offset 8 byte ke depan dalam instruksi)
//            LDR X0, label  → 0x58000040
//            LDR S0, label  → 0x1C000040
//          Nilai 0x40 = offset +8 dari PC (melewati instruksi LDR itu sendiri + RET).
//          Nilai 0x60 yang dipakai CodeGenerator.h = offset +12, SALAH karena
//          literal pool hanya 8 byte dari LDR.
//
//          Fungsi ini menjadi satu-satunya definisi yang dipakai seluruh proyek.
// ─────────────────────────────────────────────────────────────────────────────

/**
 * @brief Derive ARM64 patch bytes dari return type name + patch text value.
 *
 * Output bytes adalah instruksi ARM64 yang ketika di-execute akan:
 * - Langsung return nilai tertentu (MOV + RET atau LDR literal + RET)
 *
 * @param returnTypeName  Nama tipe kembalian, contoh "System.Boolean", "System.Int32"
 * @param patchValue      Nilai patch sebagai string, contoh "True", "1", "100", "NOP"
 * @return std::vector<uint8_t>  Byte sequence yang siap di-memcpy ke methodPointer
 */
inline std::vector<uint8_t> DerivePatchBytes(
    const std::string& returnTypeName,
    const std::string& patchValue)
{
    constexpr uint32_t RET = 0xD65F03C0;

    // void / NOP → hanya RET
    if (returnTypeName == "System.Void" || patchValue == "NOP") {
        return { 0xC0, 0x03, 0x5F, 0xD6 };
    }

    // bool → MOV W0, #1 ; RET  atau  MOV W0, #0 ; RET
    if (returnTypeName == "System.Boolean") {
        bool v = (patchValue == "True" || patchValue == "true" || patchValue == "1");
        if (v) return { 0x20, 0x00, 0x80, 0x52,   // MOVZ W0, #1
                        0xC0, 0x03, 0x5F, 0xD6 }; // RET
        else   return { 0x00, 0x00, 0x80, 0x52,   // MOVZ W0, #0
                        0xC0, 0x03, 0x5F, 0xD6 }; // RET
    }

    try {
        // int32 / uint32 → LDR W0, [pc+8] ; RET ; .word value
        if (returnTypeName == "System.Int32" || returnTypeName == "System.UInt32") {
            uint32_t v   = (uint32_t)std::stol(patchValue);
            uint32_t ldr = 0x18000040; // LDR W0, 8  (literal pool +8 dari PC)
            std::vector<uint8_t> b(12);
            memcpy(b.data() + 0, &ldr, 4);
            memcpy(b.data() + 4, &RET, 4);
            memcpy(b.data() + 8, &v,   4);
            return b;
        }

        // int64 / uint64 → LDR X0, [pc+8] ; RET ; .quad value
        if (returnTypeName == "System.Int64" || returnTypeName == "System.UInt64") {
            uint64_t v   = (uint64_t)std::stoll(patchValue);
            uint32_t ldr = 0x58000040; // LDR X0, 8
            std::vector<uint8_t> b(16);
            memcpy(b.data() + 0, &ldr, 4);
            memcpy(b.data() + 4, &RET, 4);
            memcpy(b.data() + 8, &v,   8);
            return b;
        }

        // float → LDR S0, [pc+8] ; RET ; .float value
        if (returnTypeName == "System.Single") {
            float    v   = std::stof(patchValue);
            uint32_t ldr = 0x1C000040; // LDR S0, 8
            std::vector<uint8_t> b(12);
            memcpy(b.data() + 0, &ldr, 4);
            memcpy(b.data() + 4, &RET, 4);
            memcpy(b.data() + 8, &v,   4);
            return b;
        }
    }
    catch (...) { /* stol/stof gagal → fallback RET */ }

    // Fallback: hanya RET
    return { 0xC0, 0x03, 0x5F, 0xD6 };
}

// ─────────────────────────────────────────────────────────────────────────────
// SECTION 4: File I/O  ← SINGLE SOURCE OF TRUTH
// ─────────────────────────────────────────────────────────────────────────────

/**
 * @brief Simpan string content ke file.
 *
 * Gunakan ini sebagai ganti Util::FileWriter di semua tempat.
 * Otomatis log sukses/gagal via LOGI/LOGE.
 *
 * @param content   Isi file
 * @param filePath  Path absolut lengkap (misal Util::DirCodegen()+"/file.lua")
 * @return true jika berhasil
 */
inline bool SaveFile(const std::string& content, const std::string& filePath) {
    std::ofstream out(filePath, std::ios::out | std::ios::trunc);
    if (!out.is_open()) {
        LOGE("[CodeExporter] Gagal membuka file: %s", filePath.c_str());
        return false;
    }
    out << content;
    if (out.fail()) {
        LOGE("[CodeExporter] Gagal menulis ke: %s", filePath.c_str());
        return false;
    }
    LOGI("[CodeExporter] Tersimpan: %s (%zu bytes)", filePath.c_str(), content.size());
    return true;
}

// ─────────────────────────────────────────────────────────────────────────────
// SECTION 5: Library Helpers
// ─────────────────────────────────────────────────────────────────────────────

/// Hitung ukuran region yang benar untuk sebuah library.
/// Bekerja untuk lib di-extract normal MAUPUN lib embedded di split APK.
inline size_t GetLibRegionSize(const char* libName) {
    uintptr_t base = GetLibBase(libName); // libil2cpp.so → il2cpp_base

    FILE* fp = fopen("/proc/self/maps", "r");
    if (!fp) return 0;
    char line[512];

    // Pass 1: cari entry /proc/self/maps yang contain base address
    // Ini works untuk split APK (path entry = path APK, bukan libil2cpp.so)
    char targetPath[256] = {};
    if (base) {
        while (fgets(line, sizeof(line), fp)) {
            uintptr_t s = 0, e = 0;
            sscanf(line, "%lx-%lx", &s, &e);
            if (s <= base && base < e) {
                char perms[8]={}, dev[16]={}, inode_s[32]={}, path[256]={};
                unsigned long long off = 0;
                int n = sscanf(line, "%*lx-%*lx %7s %llx %15s %31s %255[^\n]",
                               perms, &off, dev, inode_s, path);
                if (n >= 5 && path[0])
                    strncpy(targetPath, path, sizeof(targetPath)-1);
                break;
            }
        }
    }

    // Pass 2: jika ketemu path file, sum semua region untuk file itu
    if (targetPath[0]) {
        rewind(fp);
        uintptr_t firstStart = 0, lastEnd = 0;
        while (fgets(line, sizeof(line), fp)) {
            if (!strstr(line, targetPath)) continue;
            uintptr_t s = 0, e = 0;
            sscanf(line, "%lx-%lx", &s, &e);
            if (!firstStart || s < firstStart) firstStart = s;
            if (e > lastEnd) lastEnd = e;
        }
        fclose(fp);
        if (firstStart && lastEnd > firstStart)
            return lastEnd - firstStart;
    }

    // Fallback: cari by nama libName (lib di-extract ke disk normal)
    rewind(fp);
    uintptr_t firstStart = 0, lastEnd = 0;
    while (fgets(line, sizeof(line), fp)) {
        if (!strstr(line, libName)) continue;
        uintptr_t s = 0, e = 0;
        sscanf(line, "%lx-%lx", &s, &e);
        if (!firstStart || s < firstStart) firstStart = s;
        if (e > lastEnd) lastEnd = e;
    }
    fclose(fp);
    return (firstStart && lastEnd > firstStart) ? (lastEnd - firstStart) : 0;
}

// ─────────────────────────────────────────────────────────────────────────────
// SECTION 6: Patch Collection
// ─────────────────────────────────────────────────────────────────────────────

/**
 * @brief Kumpulkan semua patch aktif dari oMap menjadi list CGPatchEntry.
 *
 * Template agar bisa menerima oMap dari ClassesTab (unordered_map<MethodInfo*, OriginalMethodBytes>)
 * tanpa circular dependency.
 *
 * @tparam OMapType   unordered_map<MethodInfo*, T>  dimana T memiliki .bytes dan .text
 * @param  oMap       Map patch aktif dari ClassesTab
 * @return std::vector<CGPatchEntry>
 */
template <typename OMapType>
inline std::vector<CGPatchEntry> CollectPatches(const OMapType& oMap) {
    std::vector<CGPatchEntry> result;
    result.reserve(oMap.size());

    const char* libName = GetTargetLib();
    uintptr_t   libBase = GetLibBase(libName);
    size_t      libSize = GetLibRegionSize(libName);

    for (const auto& [method, data] : oMap) {
        if (!method || !method->methodPointer || data.bytes.empty()) continue;

        CGPatchEntry e;
        auto* klass   = method->getClass();
        e.className   = (klass && klass->getName()) ? klass->getName() : "Unknown";
        e.methodName  = method->getName()            ? method->getName()  : "method";
        e.featureName = Sanitize(e.className) + "_" + Sanitize(e.methodName);
        e.libName     = libName;
        e.libSize     = libSize;

        uintptr_t absAddr = (uintptr_t)method->methodPointer;
        e.rva = (libBase && absAddr > libBase) ? (absAddr - libBase) : absAddr;

        auto* rt          = method->getReturnType();
        e.returnTypeName  = rt ? rt->getName() : "System.Void";
        e.bytesOriginal   = data.bytes;
        e.patchText       = data.text.empty() ? "NOP" : data.text;

        // ← Panggil SATU sumber kebenaran, bukan inline lagi
        e.bytesPatched = DerivePatchBytes(e.returnTypeName, e.patchText);

        result.push_back(std::move(e));
    }
    return result;
}

// ─────────────────────────────────────────────────────────────────────────────
// SECTION 7: Lua Menu Builder
// ─────────────────────────────────────────────────────────────────────────────

/// Build isi file ModMenu_GG.lua dari list patches
inline std::string BuildLuaMenu(const std::vector<CGPatchEntry>& patches) {
    std::ostringstream lua;

    lua << "-- ============================================================\n"
        << "-- Game Guardian Mod Menu\n"
        << "-- Auto Generated by IL2CPP Tool (CodeExporter)\n"
        << "-- RVA = Offset dari base libil2cpp.so (stabil antar restart)\n"
        << "-- ============================================================\n\n";

    // ── FEATURES table ───────────────────────────────────────────────────────
    lua << "local FEATURES = {\n";
    for (size_t i = 0; i < patches.size(); i++) {
        const auto& p = patches[i];
        size_t mb = p.libSize / (1024 * 1024);
        size_t kb = (p.libSize % (1024 * 1024)) / 1024;
        lua << "    [" << (i + 1) << "] = {\n"
            << "        name    = \"" << p.className << "::" << p.methodName
                                     << " [" << p.patchText << "]\",\n"
            << "        rva     = 0x" << std::hex << p.rva << std::dec << ",\n"
            << "        lib     = \"" << p.libName << "\",\n"
            << "        libSize = " << p.libSize
                                    << ", -- " << mb << "." << kb << " MB\n"
            << "        hexON   = \"" << BytesToSpacedHex(p.bytesPatched)  << "\",\n"
            << "        hexOFF  = \"" << BytesToSpacedHex(p.bytesOriginal) << "\",\n"
            << "        enabled = false,\n"
            << "    },\n";
    }
    lua << "}\n\n";

    // ── Base finder dengan region-size filter ────────────────────────────────
    lua << "-- Cache base address agar tidak scan berulang\n"
        << "local _baseCache = {}\n"
        << "local function getBase(libName, libSize)\n"
        << "    local key = libName .. '_' .. tostring(libSize)\n"
        << "    if _baseCache[key] then return _baseCache[key] end\n"
        << "    local ranges = gg.getRangesList(libName)\n"
        << "    if not ranges or #ranges == 0 then\n"
        << "        gg.alert('\\xE2\\x9D\\x8C Library tidak ditemukan: ' .. libName)\n"
        << "        return nil\n"
        << "    end\n"
        << "    -- Sort by size descending\n"
        << "    table.sort(ranges, function(a,b)\n"
        << "        return (a['end']-a.start) > (b['end']-b.start)\n"
        << "    end)\n"
        << "    -- Jika libSize valid: cari exact match dulu\n"
        << "    if libSize and libSize > 0 then\n"
        << "        local targetMB = math.floor(libSize / 1048576)\n"
        << "        for _, r in ipairs(ranges) do\n"
        << "            if (r['end'] - r.start) == libSize then\n"
        << "                _baseCache[key] = r.start; return r.start\n"
        << "            end\n"
        << "        end\n"
        << "        -- MB-level match\n"
        << "        for _, r in ipairs(ranges) do\n"
        << "            local szMB = math.floor((r['end'] - r.start) / 1048576)\n"
        << "            if szMB == targetMB and targetMB > 0 then\n"
        << "                _baseCache[key] = r.start; return r.start\n"
        << "            end\n"
        << "        end\n"
        << "    end\n"
        << "    -- Fallback: jika libSize = 0 atau tidak ada match,\n"
        << "    -- pakai region terbesar ke-2 (untuk split APK multi-region).\n"
        << "    -- Region terbesar biasanya libunity.so atau region utama yg bukan target.\n"
        << "    local idx = (#ranges >= 2) and 2 or 1\n"
        << "    local r = ranges[idx]\n"
        << "    local sz = math.floor((r['end'] - r.start) / 1048576)\n"
        << "    gg.toast('\\xE2\\x9A\\xA0 getBase fallback: region #' .. idx .. ' (' .. sz .. ' MB)')\n"
        << "    _baseCache[key] = r.start\n"
        << "    return r.start\n"
        << "end\n\n";

    // ── Patch writer ─────────────────────────────────────────────────────────
    lua << "local function writePatch(base, rva, hexStr)\n"
        << "    if not base then return false end\n"
        << "    local addr = base + rva\n"
        << "    local t, i = {}, 0\n"
        << "    for h in string.gmatch(hexStr, '%S%S') do\n"
        << "        table.insert(t, {address = addr + i, flags = gg.TYPE_BYTE, value = h .. 'r'})\n"
        << "        i = i + 1\n"
        << "    end\n"
        << "    return gg.setValues(t) ~= nil\n"
        << "end\n\n";

    // ── Toggle ON / OFF ──────────────────────────────────────────────────────
    lua << "local function featureON(f)\n"
        << "    local base = getBase(f.lib, f.libSize)\n"
        << "    if writePatch(base, f.rva, f.hexON) then\n"
        << "        f.enabled = true\n"
        << "        gg.toast('\\xE2\\x9C\\x85 ON: ' .. f.name)\n"
        << "    end\n"
        << "end\n\n"
        << "local function featureOFF(f)\n"
        << "    local base = getBase(f.lib, f.libSize)\n"
        << "    if writePatch(base, f.rva, f.hexOFF) then\n"
        << "        f.enabled = false\n"
        << "        gg.toast('\\xE2\\x9D\\x8C OFF: ' .. f.name)\n"
        << "    end\n"
        << "end\n\n";

    // ── Menu builder ─────────────────────────────────────────────────────────
    lua << "local function buildMenu()\n"
        << "    local items = {}\n"
        << "    for _, f in ipairs(FEATURES) do\n"
        << "        local icon = f.enabled and '\\xE2\\x9C\\x85 ON  ' or '\\xE2\\x9D\\x8C OFF '\n"
        << "        table.insert(items, icon .. f.name)\n"
        << "    end\n"
        << "    table.insert(items, '\\xE2\\x9E\\x95 Semua ON')\n"
        << "    table.insert(items, '\\xE2\\x9E\\x96 Semua OFF')\n"
        << "    table.insert(items, '\\xF0\\x9F\\x9A\\xAA Keluar')\n"
        << "    return items\n"
        << "end\n\n";

    // ── Main loop ────────────────────────────────────────────────────────────
    lua << "local running = true\n"
        << "while running do\n"
        << "    local n      = #FEATURES\n"
        << "    local choice = gg.choice(buildMenu(), nil, 'IL2CPP Mod Menu | ' .. n .. ' Fitur')\n"
        << "    if not choice then\n"
        << "        running = false\n"
        << "    elseif choice <= n then\n"
        << "        local f = FEATURES[choice]\n"
        << "        if f.enabled then featureOFF(f) else featureON(f) end\n"
        << "    elseif choice == n + 1 then\n"
        << "        for _, f in ipairs(FEATURES) do featureON(f) end\n"
        << "    elseif choice == n + 2 then\n"
        << "        for _, f in ipairs(FEATURES) do featureOFF(f) end\n"
        << "    else\n"
        << "        running = false\n"
        << "    end\n"
        << "    gg.sleep(150)\n"
        << "end\n"
        << "print('[ModMenu] Selesai.')\n";

    return lua.str();
}

// ─────────────────────────────────────────────────────────────────────────────
// SECTION 8: C++ Header Builder
// ─────────────────────────────────────────────────────────────────────────────

/// Build isi file AutoGenerated.h dari list patches
inline std::string BuildCppHeader(const std::vector<CGPatchEntry>& patches) {
    std::ostringstream h;

    h << "// ============================================================\n"
      << "// AutoGenerated.h — IL2CPP Tool (CodeExporter)\n"
      << "// RVA = offset relatif dari base libil2cpp.so\n"
      << "// RVA TIDAK berubah antar restart (walaupun base ASLR berubah)\n"
      << "//\n"
      << "// Cara pakai:\n"
      << "//   uintptr_t base = GetLibBase(\"libil2cpp.so\");\n"
      << "//   PatchMemory(base + RVA_XXX, bytes_on_xxx, sizeof(bytes_on_xxx));\n"
      << "// ============================================================\n"
      << "#pragma once\n"
      << "#include <cstdint>\n"
      << "#include <cstring>\n"
      << "#include <sys/mman.h>\n"
      << "#include <unistd.h>\n\n";

    // ── GetLibBase helper ────────────────────────────────────────────────────
    h << "// ── GetLibBase: cari base library via /proc/self/maps (cached) ──\n"
      << "static uintptr_t _s_libBase = 0;\n"
      << "inline uintptr_t GetLibBase(const char* libName) {\n"
      << "    if (_s_libBase) return _s_libBase;\n"
      << "    FILE* fp = fopen(\"/proc/self/maps\", \"r\"); if (!fp) return 0;\n"
      << "    char line[512];\n"
      << "    while (fgets(line, sizeof(line), fp)) {\n"
      << "        if (!strstr(line, libName)) continue;\n"
      << "        sscanf(line, \"%lx\", &_s_libBase);\n"
      << "        if (_s_libBase) break;\n"
      << "    }\n"
      << "    fclose(fp);\n"
      << "    return _s_libBase;\n"
      << "}\n\n";

    // ── PatchMemory helper ───────────────────────────────────────────────────
    h << "// ── PatchMemory: tulis bytes ke alamat memori (mprotect + memcpy) ──\n"
      << "inline bool PatchMemory(uintptr_t addr, const uint8_t* bytes, size_t len) {\n"
      << "    if (!addr || !bytes || !len) return false;\n"
      << "    size_t    ps  = (size_t)sysconf(_SC_PAGESIZE);\n"
      << "    uintptr_t pb  = addr & ~(ps - 1);\n"
      << "    if (mprotect((void*)pb, ps, PROT_READ|PROT_WRITE|PROT_EXEC) != 0) return false;\n"
      << "    memcpy((void*)addr, bytes, len);\n"
      << "    mprotect((void*)pb, ps, PROT_READ|PROT_EXEC);\n"
      << "    __builtin___clear_cache((char*)addr, (char*)addr + len);\n"
      << "    return true;\n"
      << "}\n\n";

    // ── RVA defines & byte arrays ────────────────────────────────────────────
    h << "// ── RVA & Patch Bytes ──────────────────────────────────────────────\n";
    for (const auto& p : patches) {
        std::string UP = ToUpper(p.featureName);
        h << "// " << p.className << "::" << p.methodName
          << " → " << p.patchText << "\n"
          << "#define RVA_"      << UP << "  0x" << std::hex << p.rva << std::dec << "ULL\n"
          << "#define LIB_SIZE_" << UP << "  " << p.libSize << "ULL\n"
          << "static const uint8_t bytes_on_"  << p.featureName << "[]  = "
                  << BytesToCArray(p.bytesPatched)  << ";\n"
          << "static const uint8_t bytes_off_" << p.featureName << "[] = "
                  << BytesToCArray(p.bytesOriginal) << ";\n\n";
    }

    // ── Toggle states ────────────────────────────────────────────────────────
    h << "// ── Toggle states ─────────────────────────────────────────────────\n";
    for (const auto& p : patches)
        h << "static bool toggle_" << p.featureName << " = false;\n";
    h << "\n";

    // ── ToggleFeature_ALL ────────────────────────────────────────────────────
    h << "// ── ToggleFeature_ALL: panggil dari mod menu ImGui ────────────────\n"
      << "inline void ToggleFeature_ALL(uintptr_t base) {\n";
    for (const auto& p : patches) {
        std::string UP = ToUpper(p.featureName);
        h << "    PatchMemory(base + RVA_" << UP << ", "
          << "toggle_" << p.featureName << " ? bytes_on_" << p.featureName
          << " : bytes_off_" << p.featureName
          << ", toggle_" << p.featureName << " ? sizeof(bytes_on_" << p.featureName
          << ") : sizeof(bytes_off_" << p.featureName << "));\n";
    }
    h << "}\n\n";

    // ── Contoh DrawModMenu ───────────────────────────────────────────────────
    h << "// ── Contoh DrawModMenu (copy ke mod menu kamu) ────────────────────\n"
      << "// inline void DrawModMenu() {\n"
      << "//     uintptr_t base = GetLibBase(\"libil2cpp.so\");\n";
    for (const auto& p : patches) {
        std::string lbl = p.className + "::" + p.methodName + " [" + p.patchText + "]";
        h << "//     if (ImGui::Checkbox(\"" << lbl << "\", &toggle_"
          << p.featureName << ")) ToggleFeature_ALL(base);\n";
    }
    h << "// }\n";

    return h.str();
}

// ─────────────────────────────────────────────────────────────────────────────
// SECTION 9: ExportAll — Entry point utama
// ─────────────────────────────────────────────────────────────────────────────

/**
 * @brief Export semua patch aktif ke ModMenu_GG.lua + AutoGenerated.h
 *
 * Ini adalah entry point utama yang dipanggil dari:
 *   - ClassesTab::DrawPatchManager()
 *   - CodeGeneratorUI (jika diinginkan)
 *
 * @tparam OMapType  unordered_map<MethodInfo*, T>  (T harus punya .bytes & .text)
 * @param  oMap      Map patch aktif
 */
template <typename OMapType>
inline void ExportAll(const OMapType& oMap) {
    auto patches = CollectPatches(oMap);
    if (patches.empty()) {
        LOGE("[CodeExporter] ExportAll: tidak ada patch aktif untuk diekspor.");
        return;
    }

    const std::string dir = Util::DirCodegen();

    // 1. Lua Menu
    {
        const std::string path = dir + "/ModMenu_GG.lua";
        SaveFile(BuildLuaMenu(patches), path);
    }

    // 2. C++ Header
    {
        const std::string path = dir + "/AutoGenerated.h";
        SaveFile(BuildCppHeader(patches), path);
    }

    LOGI("[CodeExporter] ExportAll selesai: %zu patch → %s/", patches.size(), dir.c_str());
}

// ── Backward-compatible aliases ───────────────────────────────────────────────
template <typename OMapType>
inline void ExportGlobalLuaMenu(const OMapType& oMap) { ExportAll(oMap); }

template <typename OMapType>
inline void ExportAIDEHeaders(const OMapType& oMap, const char* = "libil2cpp.so") { ExportAll(oMap); }

// ─────────────────────────────────────────────────────────────────────────────
// SECTION 10: Per-Class Builders (untuk CodeGeneratorUI)
// ─────────────────────────────────────────────────────────────────────────────

/// Build Lua GG script untuk satu class (field offsets + method RVAs)
inline std::string BuildClassLua(Il2CppClass* klass);

/// Build C++ header untuk satu class (offsets namespace + struct with padding)
inline std::string BuildClassCpp(Il2CppClass* klass);

} // namespace CodeExporter

// ─────────────────────────────────────────────────────────────────────────────
// Implementasi BuildClassLua & BuildClassCpp
// (harus di bawah deklarasi namespace agar bisa pakai semua helpers di atas)
// ─────────────────────────────────────────────────────────────────────────────

inline std::string CodeExporter::BuildClassLua(Il2CppClass* klass) {
    if (!klass) return "-- No class selected\n";
    std::ostringstream ss;
    const char* cn   = klass->getName();
    auto fields      = klass->getFields();
    auto methods     = klass->getMethods();
    uintptr_t libBase = GetLibBase(GetTargetLib());

    ss << "-- ============================================================\n"
       << "-- Game Guardian Lua Script\n"
       << "-- Class   : " << (cn ? cn : "?") << "\n"
       << "-- Generated by IL2CPP Tool (CodeExporter)\n"
       << "-- RVA method = offset dari base libil2cpp.so (stabil)\n"
       << "-- ============================================================\n\n";

    // Instance field offsets
    ss << "local offsets = {\n";
    for (auto* f : fields) {
        if (!f || (Il2cpp::GetFieldFlags(f) & 0x10)) continue;
        const char* fn = f->getName(); auto* ft = f->getType();
        ss << "    " << Sanitize(fn ? fn : "unknown") << " = 0x"
           << std::hex << f->getOffset() << std::dec
           << ",  -- " << (ft ? ft->getName() : "?") << "\n";
    }
    ss << "}\n\n";

    // Static field offsets
    bool hasStatic = false;
    for (auto* f : fields) if (f && (Il2cpp::GetFieldFlags(f) & 0x10)) { hasStatic = true; break; }
    if (hasStatic) {
        ss << "local staticOffsets = {\n";
        for (auto* f : fields) {
            if (!f || !(Il2cpp::GetFieldFlags(f) & 0x10)) continue;
            const char* fn = f->getName(); auto* ft = f->getType();
            ss << "    " << Sanitize(fn ? fn : "unknown") << " = 0x"
               << std::hex << f->getOffset() << std::dec
               << ",  -- static " << (ft ? ft->getName() : "?") << "\n";
        }
        ss << "}\n\n";
    }

    // Method RVAs
    if (!methods.empty()) {
        ss << "-- Method RVA — tambahkan ke libBase untuk absolute address\n"
           << "-- local libBase = gg.getRangesList('libil2cpp.so')[1].start\n"
           << "local methodRVA = {\n";
        for (auto* m : methods) {
            if (!m || !m->getName() || !m->methodPointer) continue;
            uintptr_t abs = (uintptr_t)m->methodPointer;
            uintptr_t rva = (libBase && abs > libBase) ? (abs - libBase) : abs;
            ss << "    " << Sanitize(m->getName()) << " = 0x"
               << std::hex << rva << std::dec << ",  -- RVA\n";
        }
        ss << "}\n\n";
    }

    // Read/write helpers
    ss << "local function readField(base, name)\n"
       << "    if not offsets[name] then print('[GG] Field not found: '..name); return nil end\n"
       << "    return gg.getValues({{address=base+offsets[name], type=gg.TYPE_DWORD}})[1].value\n"
       << "end\n\n"
       << "local function writeField(base, name, value, ggType)\n"
       << "    if not offsets[name] then return false end\n"
       << "    ggType = ggType or gg.TYPE_DWORD\n"
       << "    gg.setValues({{address=base+offsets[name], type=ggType, value=value}})\n"
       << "    return true\n"
       << "end\n\n";

    // Per-field setters/getters
    for (auto* f : fields) {
        if (!f || (Il2cpp::GetFieldFlags(f) & 0x10)) continue;
        const char* fn = f->getName(); if (!fn) continue;
        auto* ft = f->getType(); const char* tn = ft ? ft->getName() : "?";
        std::string sn = Sanitize(fn), ggT = TypeToGG(tn ? tn : "?");
        ss << "local function set_" << sn << "(base,v) writeField(base,'" << sn
           << "',v,gg.TYPE_" << ggT << ") end\n"
           << "local function get_" << sn << "(base) return gg.getValues({{address=base+offsets."
           << sn << ",type=gg.TYPE_" << ggT << "}})[1].value end\n\n";
    }

    ss << "local function main()\n"
       << "    print('[GG] " << (cn ? cn : "?") << " loaded OK')\n"
       << "end\n"
       << "main()\n";

    return ss.str();
}

inline std::string CodeExporter::BuildClassCpp(Il2CppClass* klass) {
    if (!klass) return "// No class selected\n";
    std::ostringstream ss;
    const char* cn   = klass->getName();
    std::string safe = Sanitize(cn ? cn : "Unknown");
    auto fields      = klass->getFields();
    auto methods     = klass->getMethods();
    uintptr_t libBase = GetLibBase(GetTargetLib());

    ss << "// ============================================================\n"
       << "// IL2CPP Class Header: " << (cn ? cn : "?") << "\n"
       << "// Generated by IL2CPP Tool (CodeExporter)\n"
       << "// RVA = offset relatif dari GetLibBase(\"libil2cpp.so\")\n"
       << "// ============================================================\n"
       << "#pragma once\n#include <cstdint>\n\n";

    // Detect needed types
    bool needsV3=false, needsV2=false, needsQuat=false, needsStr=false;
    for (auto* f : fields) {
        if (!f) continue; auto* t = f->getType(); if (!t) continue;
        const char* tn = t->getName(); if (!tn) continue;
        if (strstr(tn,"Vector3"))    needsV3   = true;
        if (strstr(tn,"Vector2"))    needsV2   = true;
        if (strstr(tn,"Quaternion")) needsQuat = true;
        if (strstr(tn,"String"))     needsStr  = true;
    }
    if (needsV2)   ss << "struct Vector2 { float x, y; };\n";
    if (needsV3)   ss << "struct Vector3 { float x, y, z; };\n";
    if (needsQuat) ss << "struct Quaternion { float x, y, z, w; };\n";
    if (needsV2 || needsV3 || needsQuat) ss << "\n";
    if (needsStr)  ss << "struct Il2CppString; // Forward declare\n\n";

    // Field offset namespace
    ss << "namespace " << safe << "Offsets {\n";
    for (auto* f : fields) {
        if (!f || (Il2cpp::GetFieldFlags(f) & 0x10)) continue;
        const char* fn = f->getName(); auto* ft = f->getType();
        ss << "    constexpr uintptr_t " << Sanitize(fn ? fn : "unknown")
           << " = 0x" << std::hex << f->getOffset() << std::dec
           << ";  // " << (ft ? ft->getName() : "?") << "\n";
    }
    bool hasStatic = false;
    for (auto* f : fields) if (f && (Il2cpp::GetFieldFlags(f) & 0x10)) { hasStatic = true; break; }
    if (hasStatic) {
        ss << "\n    // Static fields\n";
        for (auto* f : fields) {
            if (!f || !(Il2cpp::GetFieldFlags(f) & 0x10)) continue;
            const char* fn = f->getName(); auto* ft = f->getType();
            ss << "    constexpr uintptr_t " << Sanitize(fn ? fn : "unknown")
               << " = 0x" << std::hex << f->getOffset() << std::dec
               << ";  // static " << (ft ? ft->getName() : "?") << "\n";
        }
    }
    ss << "} // namespace " << safe << "Offsets\n\n";

    // Method RVA namespace
    if (!methods.empty()) {
        ss << "// Method RVA — stabil antar restart game\n"
           << "namespace " << safe << "MethodRVA {\n";
        for (auto* m : methods) {
            if (!m || !m->getName()) continue;
            const char* mn = m->getName();
            auto*    rt    = Il2cpp::GetMethodReturnType(m);
            const char* rn = rt ? Il2cpp::GetTypeName(rt) : "void";
            bool isSt      = Il2cpp::GetIsMethodStatic(m);
            uint32_t pc    = Il2cpp::GetMethodParamCount(m);
            uintptr_t abs  = m->methodPointer ? (uintptr_t)m->methodPointer : 0;
            uintptr_t rva  = (libBase && abs > libBase) ? (abs - libBase) : abs;

            ss << "    // " << (isSt ? "static " : "") << (rn ? rn : "void")
               << " " << mn << "(" << pc << " params)\n";
            if (rva)
                ss << "    constexpr uintptr_t " << Sanitize(mn)
                   << " = 0x" << std::hex << rva << std::dec << ";  // RVA\n";
            else
                ss << "    // constexpr uintptr_t " << Sanitize(mn)
                   << " = 0x0;  // null (abstract/generic)\n";
        }
        ss << "} // namespace " << safe << "MethodRVA\n\n";
    }

    // Struct with padding
    ss << "#pragma pack(push, 1)\n"
       << "struct " << safe << " {\n"
       << "    uintptr_t klass;    // 0x00  Il2CppClass*\n"
       << "    uintptr_t monitor;  // 0x08  monitor\n";

    std::vector<FieldInfo*> instFields;
    for (auto* f : fields) if (f && !(Il2cpp::GetFieldFlags(f) & 0x10)) instFields.push_back(f);
    std::sort(instFields.begin(), instFields.end(),
        [](FieldInfo* a, FieldInfo* b){ return a->getOffset() < b->getOffset(); });

    uintptr_t prevEnd = 0x10; int padIdx = 0; bool firstField = true;
    for (auto* f : instFields) {
        const char* fn = f->getName(); auto* ft = f->getType();
        const char* tn = ft ? ft->getName() : "?";
        uintptr_t offset = f->getOffset();
        std::string ct = TypeToC(tn ? tn : "?");
        size_t sz = 4;
        if (ct=="int64_t"||ct=="uint64_t"||ct=="double"||
            ct=="Il2CppObject*"||ct=="Il2CppString*") sz = 8;
        else if (ct=="int16_t"||ct=="uint16_t") sz = 2;
        else if (ct=="bool"||ct=="uint8_t")     sz = 1;
        else if (ct=="Vector3")    sz = 12;
        else if (ct=="Vector2")    sz = 8;
        else if (ct=="Quaternion") sz = 16;

        if (offset > prevEnd)
            ss << "    char pad_" << padIdx++ << "[" << (offset-prevEnd)
               << "];  // 0x" << std::hex << prevEnd << std::dec << " padding\n";
        else if (offset < prevEnd && !firstField)
            ss << "    // [WARNING] overlap at 0x" << std::hex << offset
               << "  (" << (fn ? fn : "?") << ")\n" << std::dec;
        firstField = false;
        ss << "    " << ct << " " << Sanitize(fn ? fn : "unknown")
           << ";  // 0x" << std::hex << offset << std::dec
           << "  " << (tn ? tn : "?") << "\n";
        prevEnd = offset + sz;
    }
    ss << "};\n#pragma pack(pop)\n\n";

    ss << "#define READ_"  << safe << "(base,field) "
       << "(*reinterpret_cast<decltype(" << safe << "::field)*>"
       << "((uintptr_t)(base)+" << safe << "Offsets::field))\n"
       << "#define WRITE_" << safe << "(base,field,val) "
       << "READ_" << safe << "(base,field)=(val)\n";

    return ss.str();
}
