// ============================================================================
// Tab_Inspector.cpp
// Implementasi floating inspector windows: Field Watch, Call Record, Export.
//
// Edit file ini untuk update tampilan/fitur inspector.
// ============================================================================

#include "Tool/Tab_Inspector.h"
#include "Tool.h"
#include "Tool/Keyboard.h"
#include "Tool/Util.h"
#include "Il2cpp/Il2cpp.h"
#include "Includes/Logger.h"
#include "Includes/Utils.h"
#include "imgui/imgui.h"
#include "imgui/imgui_internal.h"

#include <mutex>
#include <algorithm>
#include <sstream>
#include <string>
#include <vector>
#include <cstring>

extern std::unordered_map<void *, HookerData> hookerMap;
extern std::mutex hookerMtx;

std::string ReadFieldValue(void *obj, uintptr_t offset, const char *tn);

static std::string SafeReadField(void *obj, uintptr_t offset, const char *tn)
{
    if (!obj || !tn || offset == 0 || offset > 0x3000) return "?";
    try { return ReadFieldValue(obj, offset, tn); }
    catch (...) { return "ERR"; }
}

// ============================================================================
// DrawFieldWatcher — panel watch field realtime
// ============================================================================
static void DrawFieldWatcher(HookerData &hd, MethodInfo *method)
{
    float bw     = ImGui::GetContentRegionAvail().x;
    bool watching = __atomic_load_n(&hd.watchActive, __ATOMIC_ACQUIRE);

    // Tombol kontrol
    {
        ImU32 btnCol = watching ? IM_COL32(160,30,30,220) : IM_COL32(25,100,180,220);
        ImGui::PushStyleColor(ImGuiCol_Button, btnCol);
        if (ImGui::Button(watching ? "Stop Watch" : "Start Watch", ImVec2(bw * 0.38f, 0))) {
            if (!watching) {
                std::lock_guard<std::mutex> lk(hookerMtx);
                hd.watchedFields.clear(); hd.watchInstance = nullptr;
                for (auto *f : method->getClass()->getFields(true)) {
                    if (!f) continue;
                    if (Il2cpp::GetFieldFlags(f) & 0x10) continue;
                    auto *ft = f->getType(); if (!ft) continue;
                    const char *tn = ft->getName(); if (!tn) continue;
                    WatchedField wf;
                    wf.name   = f->getName() ? f->getName() : "?";
                    wf.type   = tn;
                    wf.offset = f->getOffset();
                    hd.watchedFields.push_back(std::move(wf));
                }
                __atomic_store_n(&hd.watchActive, true, __ATOMIC_RELEASE);
            } else {
                __atomic_store_n(&hd.watchActive, false, __ATOMIC_RELEASE);
            }
        }
        ImGui::PopStyleColor();
        ImGui::SameLine();

        if (ImGui::Button("Clear Changes", ImVec2(bw * 0.32f, 0))) {
            std::lock_guard<std::mutex> lk(hookerMtx);
            for (auto &wf : hd.watchedFields) wf.changed = false;
        }
        ImGui::SameLine();

        ImGui::PushStyleColor(ImGuiCol_Button, IM_COL32(25,80,140,220));
        if (ImGui::Button("Export All", ImVec2(ImGui::GetContentRegionAvail().x, 0))) {
            std::ostringstream cpp, txt;
            uintptr_t base = (uintptr_t)GetLibBase(GetTargetLib());
            const char *cn   = method->getClass()->getName();
            std::string sn   = cn ? cn : "Unknown";
            std::string ns   = method->getClass()->getNamespace() ? method->getClass()->getNamespace() : "";
            std::string asm_ = method->getClass()->getImage() ? method->getClass()->getImage()->getName() : "";

            cpp << "// Auto Generated by IL2CPP Tool\n#pragma once\n#include <cstdint>\n\n";
            cpp << "// Assembly  : " << asm_ << "\n// Namespace : " << ns << "\n// Class     : " << sn << "\n\n";
            txt << "[ Fields ] " << sn << "\nAssembly: " << asm_ << "\nNamespace: " << ns << "\n\n";

            {
                std::lock_guard<std::mutex> lk(hookerMtx);
                for (auto &wf : hd.watchedFields) {
                    std::string macro = wf.name;
                    std::replace(macro.begin(), macro.end(), '.', '_');
                    std::replace(macro.begin(), macro.end(), '<', '_');
                    std::replace(macro.begin(), macro.end(), '>', '_');
                    std::transform(macro.begin(), macro.end(), macro.begin(), ::toupper);
                    std::string label = wf.label.empty() ? wf.name : (wf.name + " (" + wf.label + ")");

                    cpp << "// " << wf.type << " " << label;
                    if (!wf.lastValue.empty()) cpp << "  last=" << wf.lastValue;
                    if (wf.changed) cpp << "  [CHANGED]";
                    cpp << "\n#define OFFSET_" << macro << "  0x" << std::hex << wf.offset << "\n\n";

                    txt << "  0x" << std::hex << wf.offset << "  " << wf.type << "  " << label;
                    if (!wf.lastValue.empty()) txt << "  = " << wf.lastValue;
                    if (wf.changed) txt << "  [CHANGED]";
                    txt << "\n";
                }
            }
            if (method->methodPointer && base) {
                uintptr_t rva = (uintptr_t)method->methodPointer - base;
                cpp << "// Method RVA\n#define RVA_" << sn << "  0x" << std::hex << rva << "\n";
                txt << "\nMethod RVA : 0x" << std::hex << rva << "\n";
            }
            std::string safe = sn; std::replace(safe.begin(), safe.end(), ' ', '_');
            Util::FileWriter(Util::DirFields(), safe + "_fields.h").write(cpp.str().c_str());
            Util::FileWriter(Util::DirFields(), safe + "_fields.txt").write(txt.str().c_str());
            Keyboard::Open((Util::DirFields() + "/" + safe + "_fields.h").c_str(), nullptr);
        }
        ImGui::PopStyleColor();
    }

    if (!watching) { ImGui::TextDisabled("Aktifkan Watch lalu main game."); return; }

    float now  = ImGui::GetTime();
    void *inst = nullptr;
    { std::lock_guard<std::mutex> lk(hookerMtx); inst = hd.watchInstance; }
    if (!inst) { ImGui::TextDisabled("Menunggu method dipanggil..."); return; }

    if (now - hd.watchLastRefresh > 0.25f) {
        hd.watchLastRefresh = now;
        std::lock_guard<std::mutex> lk(hookerMtx);
        for (auto &wf : hd.watchedFields) {
            std::string nv = SafeReadField(inst, wf.offset, wf.type.c_str());
            if (!wf.lastValue.empty() && wf.lastValue != nv) wf.changed = true;
            wf.lastValue = nv;
        }
        auto sortFn = [](const WatchedField &a, const WatchedField &b) {
            if (a.pinned != b.pinned) return a.pinned > b.pinned;
            if (a.changed != b.changed) return a.changed > b.changed;
            return a.name < b.name;
        };
        std::stable_sort(hd.watchedFields.begin(), hd.watchedFields.end(), sortFn);
    }

    size_t changedCount = std::count_if(hd.watchedFields.begin(), hd.watchedFields.end(), [](const WatchedField &wf) { return wf.changed; });
    size_t pinnedCount  = std::count_if(hd.watchedFields.begin(), hd.watchedFields.end(), [](const WatchedField &wf) { return wf.pinned; });
    ImGui::TextDisabled("@0x%llX  (4x/s) | %zu fields, %zu changed, %zu pinned",
        (unsigned long long)inst, hd.watchedFields.size(), changedCount, pinnedCount);

    float tblH = std::max(ImGui::GetContentRegionAvail().y, 60.f);
    if (ImGui::BeginTable("##WTbl", 5,
        ImGuiTableFlags_Borders | ImGuiTableFlags_RowBg |
        ImGuiTableFlags_ScrollY | ImGuiTableFlags_SizingStretchProp,
        ImVec2(0, tblH)))
    {
        ImGui::TableSetupScrollFreeze(0, 1);
        ImGui::TableSetupColumn("Type",   ImGuiTableColumnFlags_WidthStretch, 20.f);
        ImGui::TableSetupColumn("Name",   ImGuiTableColumnFlags_WidthStretch, 30.f);
        ImGui::TableSetupColumn("Value",  ImGuiTableColumnFlags_WidthStretch, 30.f);
        ImGui::TableSetupColumn("Offset", ImGuiTableColumnFlags_WidthFixed,   58.f);
        ImGui::TableSetupColumn("Pin",    ImGuiTableColumnFlags_WidthFixed,   28.f);
        ImGui::TableHeadersRow();

        std::lock_guard<std::mutex> lk(hookerMtx);
        auto sortFn = [](const WatchedField &a, const WatchedField &b) {
            if (a.pinned != b.pinned) return a.pinned > b.pinned;
            if (a.changed != b.changed) return a.changed > b.changed;
            return a.name < b.name;
        };
        for (auto &wf : hd.watchedFields) {
            ImGui::TableNextRow(); ImGui::PushID(&wf);
            if (wf.pinned)       ImGui::TableSetBgColor(ImGuiTableBgTarget_RowBg0, IM_COL32(80,60,20,100));
            else if (wf.changed) ImGui::TableSetBgColor(ImGuiTableBgTarget_RowBg0, IM_COL32(60,120,20,120));

            ImGui::TableSetColumnIndex(0); ImGui::TextDisabled("%s", wf.type.c_str());
            ImGui::TableSetColumnIndex(1);
            if (wf.pinned) ImGui::TextColored(ImVec4(1.f,.9f,.3f,1.f), "%s", wf.name.c_str());
            else           ImGui::TextUnformatted(wf.name.c_str());
            ImGui::TableSetColumnIndex(2);
            if (wf.changed) ImGui::TextColored(ImVec4(.4f,1.f,.3f,1.f), "%s", wf.lastValue.c_str());
            else            ImGui::TextDisabled("%s", wf.lastValue.c_str());
            ImGui::TableSetColumnIndex(3); ImGui::TextDisabled("0x%lX", (unsigned long)wf.offset);
            ImGui::TableSetColumnIndex(4);
            ImGui::PushStyleColor(ImGuiCol_Button, wf.pinned ? IM_COL32(200,150,20,200) : IM_COL32(50,50,50,200));
            if (ImGui::Button("Pin", ImVec2(ImGui::GetIO().DisplaySize.x * 0.10f, 0))) {
                wf.pinned = !wf.pinned;
                std::stable_sort(hd.watchedFields.begin(), hd.watchedFields.end(), sortFn);
            }
            ImGui::PopStyleColor();
            ImGui::PopID();
        }
        ImGui::EndTable();
    }
}

// ============================================================================
// DrawInspectorBody — isi panel inspector (toggle, params, fields, return)
// ============================================================================
static void DrawInspectorBody(HookerData &hd, MethodInfo *method,
                               const CallRecord &snap, bool hasData,
                               const std::vector<CallRecord> &history)
{
    auto toggleBtn = [](const char *lbl, bool *flag) {
        bool cur = __atomic_load_n(flag, __ATOMIC_ACQUIRE);
        ImGui::PushStyleColor(ImGuiCol_Button, cur ? IM_COL32(30,160,60,230) : IM_COL32(55,55,55,200));
        if (ImGui::Button(lbl, ImVec2(ImGui::GetIO().DisplaySize.x * 0.16f, 0))) __atomic_store_n(flag, !cur, __ATOMIC_RELEASE);
        ImGui::PopStyleColor(); ImGui::SameLine();
    };
    toggleBtn("Caller", &hd.trackCaller);
    toggleBtn("Params", &hd.trackParams);
    toggleBtn("Fields", &hd.trackFields);
    toggleBtn("Return", &hd.trackReturn);

    // Watch toggle
    bool watchCur = __atomic_load_n(&hd.watchActive, __ATOMIC_ACQUIRE);
    ImGui::PushStyleColor(ImGuiCol_Button, watchCur ? IM_COL32(30,160,60,230) : IM_COL32(55,55,55,200));
    if (ImGui::Button("Watch", ImVec2(ImGui::GetIO().DisplaySize.x * 0.14f, 0))) {
        if (!watchCur) {
            std::lock_guard<std::mutex> lk(hookerMtx);
            hd.watchedFields.clear(); hd.watchInstance = nullptr;
            for (auto *f : method->getClass()->getFields(true)) {
                if (!f) continue;
                if (Il2cpp::GetFieldFlags(f) & 0x10) continue;
                auto *ft = f->getType(); if (!ft) continue;
                const char *tn = ft->getName(); if (!tn) continue;
                WatchedField wf;
                wf.name = f->getName() ? f->getName() : "?";
                wf.type = tn; wf.offset = f->getOffset();
                hd.watchedFields.push_back(std::move(wf));
            }
            __atomic_store_n(&hd.watchActive, true, __ATOMIC_RELEASE);
        } else {
            __atomic_store_n(&hd.watchActive, false, __ATOMIC_RELEASE);
        }
    }
    ImGui::PopStyleColor(); ImGui::SameLine();

    // Export button
    ImGui::PushStyleColor(ImGuiCol_Button, IM_COL32(25,70,140,220));
    if (ImGui::Button("Export", ImVec2(ImGui::GetIO().DisplaySize.x * 0.14f, 0)) && hasData) {
        std::ostringstream cpp, txt;
        uintptr_t base = (uintptr_t)GetLibBase(GetTargetLib());
        uintptr_t rva  = (method->methodPointer && base) ? (uintptr_t)method->methodPointer - base : 0;
        const char *cn = method->getClass() ? method->getClass()->getName() : "?";
        const char *mn = method->getName()  ? method->getName()             : "?";
        std::string ns   = method->getClass() && method->getClass()->getNamespace() ? method->getClass()->getNamespace() : "";
        std::string asm_ = method->getClass() && method->getClass()->getImage() ? method->getClass()->getImage()->getName() : "";

        cpp << "// Inspector Export: " << cn << "::" << mn << "\n";
        cpp << "// Assembly: " << asm_ << "  Namespace: " << ns << "  RVA: 0x" << std::hex << rva << "\n";
        cpp << "#pragma once\n#include <cstdint>\n\n";
        if (rva) {
            std::string mMacro = mn;
            std::replace(mMacro.begin(), mMacro.end(), '.', '_');
            std::transform(mMacro.begin(), mMacro.end(), mMacro.begin(), ::toupper);
            cpp << "#define RVA_" << mMacro << "  0x" << std::hex << rva << "\n\n";
        }
        cpp << "// [ Fields ]\n";
        for (auto &f : snap.fields) {
            std::string m2 = f.name;
            std::replace(m2.begin(), m2.end(), '.', '_');
            std::replace(m2.begin(), m2.end(), '<', '_');
            std::replace(m2.begin(), m2.end(), '>', '_');
            std::transform(m2.begin(), m2.end(), m2.begin(), ::toupper);
            cpp << "// " << f.type << " " << f.name << "  last=" << f.value << "\n";
            cpp << "#define OFFSET_" << m2 << "  0x" << std::hex << f.offset << "\n\n";
        }
        if (!snap.caller.empty()) cpp << "// Caller: " << snap.caller << "\n";
        if (snap.hasReturn) cpp << "// Return: " << snap.retValue << "\n";

        txt << "Inspector: " << cn << "::" << mn << "\nRVA: 0x" << std::hex << rva << "\n";
        if (!snap.params.empty()) {
            txt << "\n[ Params ]\n";
            for (auto &p : snap.params) txt << "  " << p.type << " " << p.name << " = " << p.value << "\n";
        }
        if (!snap.fields.empty()) {
            txt << "\n[ Fields ]\n";
            for (auto &f : snap.fields)
                txt << "  0x" << std::hex << f.offset << "  " << f.type << "  " << f.name << " = " << f.value << "\n";
        }
        if (snap.hasReturn) txt << "\nReturn: " << snap.retValue << "\n";

        std::string safe = std::string(cn) + "_" + mn;
        std::replace(safe.begin(), safe.end(), ' ', '_');
        std::replace(safe.begin(), safe.end(), '.', '_');
        Util::FileWriter(Util::DirInspector(), safe + "_inspector.h").write(cpp.str().c_str());
        Util::FileWriter(Util::DirInspector(), safe + "_inspector.txt").write(txt.str().c_str());
        Keyboard::Open((Util::DirInspector() + "/" + safe + "_inspector.h").c_str(), nullptr);
    }
    ImGui::PopStyleColor();

    // Field Watch sub-panel
    if (__atomic_load_n(&hd.watchActive, __ATOMIC_ACQUIRE)) {
        ImGui::Separator();
        ImGui::TextColored(ImVec4(1.f,.75f,.1f,1.f), "[ FIELD WATCH ]");
        DrawFieldWatcher(hd, method); return;
    }

    if (!hasData) {
        ImGui::Spacing();
        bool anyOn = hd.trackCaller || hd.trackParams || hd.trackFields || hd.trackReturn;
        ImGui::TextDisabled(anyOn ? "  Menunggu method dipanggil..." : "  Aktifkan toggle di atas.");
        return;
    }

    float avail = std::max(ImGui::GetContentRegionAvail().y - 52.f, 60.f);
    ImGui::BeginChild("##IWBody", ImVec2(0, avail), false);
    ImGui::TextDisabled("Call #%u", snap.index);
    ImGui::Separator();

    if (hd.trackCaller) {
        ImGui::TextColored(ImVec4(.4f,.85f,1.f,1.f), "[ CALLER ]"); ImGui::SameLine();
        if (snap.caller.empty()) ImGui::TextDisabled("(native)");
        else ImGui::TextWrapped("%s", snap.caller.c_str());
        ImGui::Separator();
    }

    if (hd.trackParams) {
        ImGui::TextColored(ImVec4(1.f,.8f,.3f,1.f), "[ PARAMS ]");
        if (snap.params.empty()) { ImGui::SameLine(); ImGui::TextDisabled("(none)"); }
        else if (ImGui::BeginTable("##PT", 3, ImGuiTableFlags_BordersInnerV | ImGuiTableFlags_RowBg | ImGuiTableFlags_SizingStretchProp)) {
            ImGui::TableSetupColumn("Type", ImGuiTableColumnFlags_WidthStretch, 28.f);
            ImGui::TableSetupColumn("Name", ImGuiTableColumnFlags_WidthStretch, 26.f);
            ImGui::TableSetupColumn("Val",  ImGuiTableColumnFlags_WidthStretch, 46.f);
            ImGui::TableHeadersRow();
            for (auto &p : snap.params) {
                ImGui::TableNextRow();
                ImGui::TableSetColumnIndex(0); ImGui::TextDisabled("%s", p.type.c_str());
                ImGui::TableSetColumnIndex(1); ImGui::TextColored(ImVec4(1,.9f,.5f,1), "%s", p.name.c_str());
                ImGui::TableSetColumnIndex(2); ImGui::TextUnformatted(p.value.c_str());
            }
            ImGui::EndTable();
        }
        ImGui::Separator();
    }

    if (hd.trackFields) {
        ImGui::TextColored(ImVec4(.4f,1.f,.55f,1.f), "[ FIELDS ]");
        if (snap.thisPtr) { ImGui::SameLine(); ImGui::TextDisabled("@0x%llX", (unsigned long long)snap.thisPtr); }
        if (!snap.fields.empty()) {
            float tH = std::min((float)snap.fields.size() * 22.f + 28.f, 220.f);
            if (ImGui::BeginTable("##FT", 5,
                ImGuiTableFlags_BordersInnerV | ImGuiTableFlags_RowBg |
                ImGuiTableFlags_ScrollY | ImGuiTableFlags_SizingStretchProp,
                ImVec2(0, tH)))
            {
                ImGui::TableSetupScrollFreeze(0, 1);
                ImGui::TableSetupColumn("Type",  ImGuiTableColumnFlags_WidthStretch, 22.f);
                ImGui::TableSetupColumn("Name",  ImGuiTableColumnFlags_WidthStretch, 26.f);
                ImGui::TableSetupColumn("Value", ImGuiTableColumnFlags_WidthStretch, 26.f);
                ImGui::TableSetupColumn("Off",   ImGuiTableColumnFlags_WidthFixed,   58.f);
                ImGui::TableSetupColumn("Edit",  ImGuiTableColumnFlags_WidthFixed,   34.f);
                ImGui::TableHeadersRow();
                for (auto &f : snap.fields) {
                    ImGui::TableNextRow(); ImGui::PushID((void*)(uintptr_t)f.offset);
                    ImGui::TableSetColumnIndex(0); ImGui::TextDisabled("%s", f.type.c_str());
                    ImGui::TableSetColumnIndex(1);
                    bool isNum = (f.type == "System.Single" || f.type == "System.Double" ||
                                  f.type == "System.Int32"  || f.type == "System.UInt32");
                    ImGui::TextColored(isNum ? ImVec4(.4f,.9f,1,1) : ImVec4(1,1,1,1), "%s", f.name.c_str());
                    ImGui::TableSetColumnIndex(2); ImGui::TextUnformatted(f.value.c_str());
                    ImGui::TableSetColumnIndex(3); ImGui::TextDisabled("0x%lX", (unsigned long)f.offset);
                    ImGui::TableSetColumnIndex(4);
                    if (f.canEdit && snap.thisPtr) {
                        if (ImGui::Button("Edit", ImVec2(ImGui::GetIO().DisplaySize.x * 0.12f, 0))) {
                            static CapturedField et; static void *eo;
                            et = f; eo = snap.thisPtr;
                            Keyboard::Open(f.value.c_str(), [](const std::string &nv) {
                                if (!eo) return;
                                uint8_t *b = (uint8_t*)eo + et.offset;
                                try {
                                    if      (et.type == "System.Boolean") { bool v = (nv=="true"||nv=="1"||nv=="True"); memcpy(b,&v,1); }
                                    else if (et.type == "System.Int32")   { int32_t  v = std::stoi(nv);                  memcpy(b,&v,4); }
                                    else if (et.type == "System.UInt32")  { uint32_t v = (uint32_t)std::stoul(nv);       memcpy(b,&v,4); }
                                    else if (et.type == "System.Int64")   { int64_t  v = std::stoll(nv);                  memcpy(b,&v,8); }
                                    else if (et.type == "System.UInt64")  { uint64_t v = (uint64_t)std::stoull(nv);      memcpy(b,&v,8); }
                                    else if (et.type == "System.Single")  { float    v = std::stof(nv);                  memcpy(b,&v,4); }
                                    else if (et.type == "System.Double")  { double   v = std::stod(nv);                  memcpy(b,&v,8); }
                                    else if (et.type == "System.Byte")    { uint8_t  v = (uint8_t)std::stoul(nv);        memcpy(b,&v,1); }
                                    else if (et.type == "System.Int16")   { int16_t  v = (int16_t)std::stoi(nv);         memcpy(b,&v,2); }
                                    else if (et.type == "System.UInt16")  { uint16_t v = (uint16_t)std::stoul(nv);       memcpy(b,&v,2); }
                                } catch (...) { LOGE("Edit field: parse error"); }
                            });
                        }
                    } else ImGui::TextDisabled("---");
                    ImGui::PopID();
                }
                ImGui::EndTable();
            }
        } else ImGui::TextDisabled("  (no fields / static)");
        ImGui::Separator();
    }

    if (hd.trackReturn) {
        ImGui::TextColored(ImVec4(1.f,.45f,.45f,1.f), "[ RETURN ]"); ImGui::SameLine();
        if (!snap.hasReturn) ImGui::TextDisabled("(waiting...)");
        else {
            auto *rt = method->getReturnType();
            if (rt) { ImGui::TextDisabled("%s", rt->getName()); ImGui::SameLine(); }
            ImGui::Text("-> %s", snap.retValue.c_str());
        }
    }

    { static float fsInsp = -1.f;
      auto &io2 = ImGui::GetIO();
      if (ImGui::IsWindowHovered(ImGuiHoveredFlags_AllowWhenBlockedByActiveItem)) {
          if (io2.MouseDown[0]) {
              if (fsInsp >= 0.f) ImGui::SetScrollY(ImGui::GetScrollY() + (fsInsp - io2.MousePos.y));
              fsInsp = io2.MousePos.y;
          } else fsInsp = -1.f;
      } else fsInsp = -1.f; }
    ImGui::EndChild();

    // History bar
    if (!history.empty()) {
        ImGui::PushStyleColor(ImGuiCol_ChildBg, IM_COL32(10,10,25,230));
        ImGui::BeginChild("##IWHist", ImVec2(0, 44), false, ImGuiWindowFlags_HorizontalScrollbar);
        ImGui::TextDisabled("History:"); bool first = true;
        for (auto rit = history.rbegin(); rit != history.rend(); ++rit) {
            ImGui::SameLine();
            if (!first) { ImGui::TextDisabled("|"); ImGui::SameLine(); }
            first = false;
            char mini[48]{0};
            if (rit->hasReturn && !rit->retValue.empty())
                snprintf(mini, sizeof(mini), "#%u->%s", rit->index, rit->retValue.c_str());
            else
                snprintf(mini, sizeof(mini), "#%u", rit->index);
            ImGui::PushID((int)rit->index);
            ImGui::PushStyleColor(ImGuiCol_Button, IM_COL32(30,55,30,180));
            if (ImGui::SmallButton(mini)) {
                std::lock_guard<std::mutex> lk(hookerMtx);
                hd.lastCall = *rit; hd.callReady = true;
            }
            ImGui::PopStyleColor(); ImGui::PopID();
        }
        ImGui::EndChild(); ImGui::PopStyleColor();
    }
}

// ============================================================================
// InspectorTab::DrawWindows — entry point, dipanggil tiap frame
// ============================================================================
void InspectorTab::DrawWindows()
{
    auto &io = ImGui::GetIO();
    for (auto &[ptr, hd] : hookerMap) {
        if (!hd.inspectorOpen || !hd.method) continue;

        const char *cn = hd.method->getClass() ? hd.method->getClass()->getName() : "?";
        const char *mn = hd.method->getName()  ? hd.method->getName()             : "?";
        char title[256]{0};
        snprintf(title, sizeof(title), "[Inspector] %s::%s###insp%p", cn, mn, ptr);

        ImGui::SetNextWindowSize(ImVec2(io.DisplaySize.x * 0.88f, io.DisplaySize.y * 0.58f), ImGuiCond_FirstUseEver);
        ImGui::SetNextWindowPos( ImVec2(io.DisplaySize.x * 0.06f, io.DisplaySize.y * 0.20f), ImGuiCond_FirstUseEver);
        ImGui::SetNextWindowBgAlpha(0.97f);

        bool open = true;
        if (!ImGui::Begin(title, &open, ImGuiWindowFlags_NoCollapse))
        { ImGui::End(); if (!open) hd.inspectorOpen = false; continue; }
        if (!open) { hd.inspectorOpen = false; ImGui::End(); continue; }

        ImGui::PushStyleColor(ImGuiCol_ChildBg, IM_COL32(18,42,18,230));
        ImGui::BeginChild("##IWHdr", ImVec2(0, 34), false);
        ImGui::TextColored(ImVec4(.3f,1.f,.3f,1.f), "TRACED");
        ImGui::SameLine(); ImGui::TextDisabled("|");
        ImGui::SameLine(); ImGui::Text("Hit:%d", hd.hitCount);
        ImGui::SameLine(); ImGui::TextDisabled("|");
        ImGui::SameLine();
        auto *rt = hd.method->getReturnType();
        ImGui::TextDisabled("%s %s::%s", rt ? rt->getName() : "?", cn, mn);
        ImGui::EndChild(); ImGui::PopStyleColor();

        CallRecord snap; std::vector<CallRecord> history; bool hasData = false;
        {
            std::lock_guard<std::mutex> lk(hookerMtx);
            if (hd.callReady) {
                snap = hd.lastCall; hasData = true;
                for (auto &r : hd.callHistory) history.push_back(r);
            }
        }

        DrawInspectorBody(hd, hd.method, snap, hasData, history);
        ImGui::End();
    }
}
